openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: Test
          content:
            application/json:
              x-type:
                $ref: '#/components/x-types/CorrectAnd'
              example:
                foo: wrong!
                wrong: not-expected!
            application/problems+json:
              x-type:
                WrongAndFormat:
                  $and: # Expected an array!
                    foo: boolean
                    bar: number
                Empty: # Cannot merge empty lists!
                  $and: []
                ImpossibleArraysCombination:
                  $and: # Cannot combine arrays!
                    - array: string
                    - array: number
              examples:
                Correct:
                  value: {}
                Incorrect:
                  value:
                    unexpected: fails
            application/undefined+json:
              x-type:
                $and: [] # should not produce a schema

components:
  x-types:
    CorrectAnd:
      $and:
        - foo: boolean
        - bar: number
