openapi: 3.1.0
info:
  title: Test internal $refs
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: An object with refs
          content:
            application/json:
              x-type:
                AFieldWithRegularRef:
                  $ref: '#/components/x-types/Foo'
                AFieldWithInlineRef: $ref:#/components/x-types/Foo
              examples:
                Correct:
                  value:
                    AFieldWithInlineRef: az
                    AFieldWithRegularRef: bukh
                Incorrect:
                  value:
                    AFieldWithInlineRef: wrong
                    AFieldWithRegularRef: wrong
                    NonExistingField: wrong
        201:
          description: A bare ref
          content:
            application/json:
              x-type: $ref:#/components/x-types/Foo
              examples:
                Correct:
                  value: az
        202:
          description: A file reference
          content:
            application/json:
              x-type: $ref:number.json
              examples:
                Correct:
                  value: 42
                Incorrect:
                  value: false
        203:
          description: A transitive reference
          content:
            application/json:
              x-type: $ref:#/components/x-types/Bar
              examples:
                Correct:
                  value: [az]
                Incorrect:
                  value: anything
        404:
          description: A wrong ref
          content:
            application/json:
              x-type:
                AWrongRef: $ref:wrong-file.yaml
              example:
                AWrongRef: Accepts anything
components:
  x-types:
    Foo:
      - az
      - bukh
    Bar:
      array: $ref:#/components/x-types/Foo
