openapi: 3.1.0
info:
  title: Test external nested $refs
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: An object with refs
          content:
            application/json:
              x-type:
                $ref: external-refs.yaml#/Az
              examples:
                Correct:
                  value:
                    - true
                    - false
                    - [false, true]
                Incorrect:
                  value:
                    - wrong, should be a boolean value
                    - false # this is still correct
        404:
          description: A wrong ref
          content:
            application/json:
              x-type:
                AWrongRef:
                  $ref: external-refs.yaml#/NotExistingField
              example:
                AWrongRef: Accepts anything
# TODO: investigate how does it works without referencing the external-refs.yaml in the components (compare to x-types-described-with-x-types.yaml)
# components:
#   x-types:
#     $ref: external-refs.yaml
