openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: An object with refs
          content:
            application/json:
              x-type:
                AFieldWithRegularRef:
                  $ref: "#/components/x-types/Foo"
                AFieldWithInlineRef: $ref:#/components/x-types/Foo
              examples:
                Correct:
                  value:
                    AFieldWithInlineRef: something
                    AFieldWithRegularRef: anything
                Incorrect:
                  value:
                    NonExistingField: wrong
        201:
          description: A bare ref
          content:
            application/json:
              x-type: $ref:#/components/x-types/Foo
              examples:
                Correct:
                  value: Anything
        202:
          description: A file reference
          content:
            application/json:
              x-type: $ref:number.json
              examples:
                Correct:
                  value: 42
                Incorrect:
                  value: false
        404:
          description: A wrong ref
          content:
            application/json:
              x-type:
                AWrongRef: $ref:wrong-file.yaml
              example:
                AWrongRef: Accepts anything
components:
  x-types:
    Foo: any
