openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: Test literal $schema
          content:
            application/json:
              x-type:
                $schema:
                  type: string
              example: Should pass.

            application/problems+json:
              x-type:
                WrongSchemaFormat:
                  $schema:
                    type: object
                    properties:
                      Correct:
                        type: string
                      Wrong:
                        type: wrong!
                    unexpected-property: Should fail!
                Referenced:
                  $schema:
                    $ref: '#/components/schemas/Foo'

components:
  schemas:
    Foo:
      type: string
      not-expected: Should fail!
