openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: Test
          content:
            application/json:
              x-type:
                AWrongRef: $ref:wrong-file.yaml
